- name: create apps namespace
  kubernetes.core.k8s:
    kubeconfig: /home/dawid/.kube/config
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: apps
        labels:
          name: apps

- name: create home-budget secret
  kubernetes.core.k8s:
    kubeconfig: /home/dawid/.kube/config
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: home-budget-db-secrets
        namespace: apps
      type: Opaque
      stringData:
        DB_URL: "{{ home_budget_db_url }}"
        DB_USERNAME: "{{ home_budget_db_username }}"
        DB_PASSWORD: "{{ home_budget_db_password }}"


- name: create home-budget deployment
  kubernetes.core.k8s:
    kubeconfig: /home/dawid/.kube/config
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: home-budget
        namespace: apps
        labels:
          app: home-budget
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: home-budget
        template:
          metadata:
            labels:
              app: home-budget
          spec:
            containers:
            - name: home-budget
              image: dawidkaszuba/home-budget:1.14.0
              ports:
              - containerPort: 8080
              envFrom:
                - secretRef:
                    name: home-budget-db-secrets
              readinessProbe:
                httpGet:
                  path: /actuator/health/readiness
                  port: 8080
                initialDelaySeconds: 14
                periodSeconds: 5
                failureThreshold: 3
                timeoutSeconds: 3
              livenessProbe:
                httpGet:
                  path: /actuator/health/liveness
                  port: 8080
                initialDelaySeconds: 30
                periodSeconds: 10
                failureThreshold: 3


- name: create home-budget service
  kubernetes.core.k8s:
    kubeconfig: /home/dawid/.kube/config
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: home-budget-service
        namespace: apps
      spec:
        selector:
          app: home-budget
        ports:
          - protocol: TCP
            port: 8080
            targetPort: 8080
            nodePort: 30452
        type: NodePort

- name: create home-budget ingress
  kubernetes.core.k8s:
    kubeconfig: /home/dawid/.kube/config
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: home-budget-ingress
        namespace: apps
      spec:
        ingressClassName: nginx
        tls:
          - hosts:
              - home-budget.local
            secretName: home-budget-tls
        rules:
          - host: home-budget.local
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: home-budget-service
                      port:
                        number: 8080

- name: create dir for certs
  delegate_to: localhost
  file:
    path: /home/dawid/.ansible/home-budget-tls
    state: directory
    owner: dawid
    group: dawid
    mode: '0755'

- name: check whether home-budget-tls file exists
  delegate_to: localhost
  ansible.builtin.stat:
    path: /home/dawid/.ansible/home-budget-tls/tls.crt
  register: home_budget_tls_file

- name: check whether home-budget-tls-key file exists
  delegate_to: localhost
  ansible.builtin.stat:
    path: /home/dawid/.ansible/home-budget-tls/tls.key
  register: home_budget_tls_file_key

- name: create TLS cert
  delegate_to: localhost
  command: openssl req -x509 -newkey rsa:2048 -nodes -keyout tls.key -out tls.crt -days 365 -subj "/CN=home-budget.local"
  args:
    chdir: /home/dawid/.ansible/home-budget-tls
  when: not (home_budget_tls_file.stat.exists and home_budget_tls_file_key.stat.exists)

- name: set restrictive permissions on TLS key
  delegate_to: localhost
  file:
    path: /home/dawid/.ansible/home-budget-tls/tls.key
    mode: '0600'
  when: not (home_budget_tls_file.stat.exists and home_budget_tls_file_key.stat.exists)

- name: create home-budget-tls secret
  kubernetes.core.k8s:
    kubeconfig: /home/dawid/.kube/config
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: home-budget-tls
        namespace: apps
      stringData:
        tls.crt: "{{ lookup('file', '/home/dawid/.ansible/home-budget-tls/tls.crt') }}"
        tls.key: "{{ lookup('file', '/home/dawid/.ansible/home-budget-tls/tls.key') }}"
      type: kubernetes.io/tls
