apiVersion: v1
kind: Service
metadata:
  name: {{ include "home-budget.fullname" . }}-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "home-budget.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort"}}
      nodePort: {{ .Values.service.nodePort }}
      {{- end}}
  selector:
    {{- include "home-budget.selectorLabels" . | nindent 4 }}
